# Generated by Django 2.2.4 on 2021-05-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
